
const types = {
    ADD_NUMBER_OF_PROPOSITION:"ADD_NUMBER_OF_PROPOSITION",
    SUBTRACT_NUMBER_OF_PROPOSITION:"SUBTRACT_NUMBER_OF_PROPOSITION",
    SET_HUNGER_BIG:"SET_HUNGER_BIG",
    SET_HUNGER_NORMAL:"SET_HUNGER_NORMAL",
    SET_HUNGER_FEW:"SET_HUNGER_FEW",
    SET_PREPARATING_TIME:"SET_PREPARATING_TIME",
    SET_COOKING_TIME:"SET_COOKING_TIME",
    SET_FAVORITES_RECIPES:"SET_FAVORITES_RECIPES",
    TURN_FILTER:"TURN_FILTER"
}

export default types;